language: c

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade --force-yes
  - sudo apt-get install --force-yes build-essential autoconf postgresql-server-dev-${POSTGRESQL_VERSION} postgresql-plperl-${POSTGRESQL_VERSION} libpq-dev

before_script:
  - sudo service postgresql start ${POSTGRESQL_VERSION}

script:
  - psql -U postgres -c "SELECT version()"

env:
  matrix:
    - POSTGRESQL_VERSION=9.1
    - POSTGRESQL_VERSION=9.2
    - POSTGRESQL_VERSION=9.3